FROM node:16.15.0

ENV TZ=Asia/Tokyo
ARG USERNAME=node

WORKDIR /myapp-frontend
RUN chown -R ${USERNAME} /myapp-frontend
RUN corepack enable npm

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
  && mkdir /commandhistory \
  && touch /commandhistory/.bash_history \
  && chown -R ${USERNAME} /commandhistory \
  && echo $SNIPPET >> "/home/${USERNAME}/.bashrc"
RUN mkdir -p /home/$USERNAME/.vscode-server/extensions \
    && chown -R $USERNAME /home/$USERNAME/.vscode-server

USER ${USERNAME}

EXPOSE 3000
CMD ["yarn", "dev"]
